---
- name: Install docker daemon
  ansible.builtin.include_role:
    name: geerlingguy.docker
  vars:
    docker_install_compose_plugin: true
    docker_install_compose: false

- name: Ensure python3 pip module is installed
  ansible.builtin.include_role:
    name: pip

- name: Ensure docker and docker-compose python modules are installed
  ansible.builtin.pip:
    name:
      - docker
      - docker-compose
      - pyopenssl

- name: Add A record to Cloudflare
  ansible.builtin.include_role:
    name: cloudflare
  vars:
    records:
      - cloudflare_domain: "{{ xray_domain }}"
        cloudflare_subdomain: "{{ xray_subdomain }}"
      # - cloudflare_domain: "{{ xray_domain }}"
      #   cloudflare_subdomain: "stats.{{ xray_subdomain }}"

- name: Ensure x-ui certs directory exists {{ haproxy_data_dir }}
  ansible.builtin.file:
    path: "{{ haproxy_data_dir }}"
    state: directory
    mode: "0755"

- name: Install project files
  ansible.builtin.template:
    src: "{{ item.src }}.j2"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode | default('0644') }}"
  loop:
    - src: docker-compose.yaml
      dest: "{{ haproxy_project_dir }}/docker-compose.yaml"
      # - src: env
    - src: haproxy.cfg
      dest: "{{ haproxy_data_dir }}/haproxy.cfg"

- name: Copy haproxy static files to project dir `{{ haproxy_data_dir }}`
  ansible.builtin.copy:
    src: files/{{ item }}
    dest: "{{ haproxy_data_dir }}/{{ item }}"
    mode: "0644"
  loop:
    - certificate.pem
    - decoy.html
    - static.html

- name: Create and start compose services
  community.docker.docker_compose:
    project_src: "{{ haproxy_project_dir }}"
    pull: true
    state: present

- name: Debug panel info
  ansible.builtin.debug:
    msg: |
      HAProxy stats URL: https://stats.{{ xray_subdomain }}.{{ xray_domain }}:{{ haproxy_stats_port }}/stats
      stats_user: {{ haproxy_stats_user }}
      stats_password: {{ haproxy_stats_password }}
