---
# - name: Update apt cache.
#   apt: update_cache=true cache_valid_time=600
#   when: ansible_os_family == 'Debian'
#   changed_when: false

- name: Install the latest version packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - "{{ PKGS_LIST }}"
  when: ansible_os_family == 'Debian'

# - name: Install dependencies (RedHat).
#   yum: name={{ item }} state=present
#   when: ansible_os_family == 'RedHat'
#   with_items:
#     - cronie
#     - epel-release

# - name: Install cron (Debian).
#   apt: name=cron state=present
#   when: ansible_os_family == 'Debian'


# - name: disable default services
#   ansible.builtin.service:
#     name: "{{ item }}"
#     state: stopped
#     enabled: no
#   with_items:
#     - privoxy
#     - tor
