---
- name: Install nginx
  ansible.builtin.include_role:
    name: packages
  vars:
    pkgs_list: "{{ nginx_pkgs_list }}"

- name: Copy websites
  ansible.builtin.copy:
    src: files/var/www/html
    dest: /var/www/

- name: Change worker connections
  ansible.builtin.lineinfile:
    path: /etc/nginx/nginx.conf
    regexp: worker_connections
    line: worker_connections 8192;

- name: Check if /etc/nginx/sites-enabled exists
  ansible.builtin.stat:
    path: /etc/nginx/sites-enabled
  register: sites_enabled_stat

- name: Set default path to /etc/nginx/sites-enabled
  ansible.builtin.set_fact:
    nginx_config_dir: /etc/nginx/sites-enabled
  when: sites_enabled_stat.stat.isdir

- name: Set default path to /etc/nginx/conf.d
  ansible.builtin.set_fact:
    nginx_config_dir: /etc/nginx/conf.d
  when: not sites_enabled_stat.stat.isdir

- name: Delete nginx default config
  ansible.builtin.file:
    path: "{{ nginx_config_dir }}/default"
    state: absent

- name: Install nginx config
  ansible.builtin.template:
    src: nginx-uds.conf.j2
    dest: "{{ nginx_config_dir }}/uds.conf"
    owner: root
    group: root
    mode: "0644"
    # backup: true
    # validate: nginx -t -c %s
  # register: install_config_result

- name: Check nginx config
  ansible.builtin.command: nginx -t
  tags:
    - restart-services

- name: Remove nginx socket files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /dev/shm/nginx-h1.sock
    - /dev/shm/nginx-h2c.sock
  tags:
    - restart-services

- name: Restart nginx service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: true
  tags:
    - restart-services
