- name: Generate EC key
  community.crypto.openssl_privatekey:
    path: "{{ xui_certificate_key_path }}"
  register: keygen_result

- name: Create certificate signing request (CSR) for self-signed certificate
  community.crypto.openssl_csr_pipe:
    privatekey_path: "{{ xui_certificate_key_path }}"
    common_name: "{{ xui_fake_domain }}"
    organization_name: Kawabanga, Inc.
    subject_alt_name:
      - "DNS:{{ xui_fake_domain }}"
      - "DNS:www.{{ xui_fake_domain }}"
      - "DNS:api.{{ xui_fake_domain }}"
  register: csr
  when: keygen_result.changed

- name: Create self-signed certificate from CSR
  community.crypto.x509_certificate:
    path: "{{ xui_certificate_path }}"
    csr_content: "{{ csr.csr }}"
    privatekey_path: "{{ xui_certificate_key_path }}"
    provider: selfsigned
  when: keygen_result.changed