---
- name: Install docker daemon
  ansible.builtin.include_role:
    name: geerlingguy.docker
  vars:
    docker_install_compose_plugin: false
    # docker_compose_package: docker-compose-plugin
    # docker_compose_package_state: present

- name: Ensure python3 pip module is installed
  ansible.builtin.include_role:
    name: pip

- name: Ensure docker and docker-compose python modules are installed
  ansible.builtin.pip:
    name:
      - docker
      - docker-compose
      - pyopenssl

- name: Log into DockerHub
  community.docker.docker_login:
    username: "{{ dockerhub_username }}"
    password: "{{ dockerhub_password }}"

- name: Add A record to Cloudflare
  ansible.builtin.include_role:
    name: cloudflare
  vars:
    records:
      - cloudflare_domain: "{{ xui_domain }}"
        cloudflare_subdomain: "{{ xui_subdomain }}"

- name: Get certificate for 3x-ui setup with certbot
  ansible.builtin.include_role:
    name: geerlingguy.certbot
  vars:
    certbot_certs:
      - domains:
          - "{{ xray_subdomain }}.{{ xray_domain }}"

- name: Ensure x-ui directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ xui_data_dir }}/certs"
    - "{{ xui_project_dir }}/html"

- name: Copy '{{ xray_subdomain }}.{{ xray_domain }}' certificate to {{ xui_data_dir }}
  ansible.builtin.copy:
    src: "/etc/letsencrypt/live/{{ xray_subdomain }}.{{ xray_domain }}/{{ item }}"
    dest: "{{ xui_data_dir }}/certs/{{ item }}"
    mode: "0644"
    remote_src: true
  loop:
    - fullchain.pem
    - privkey.pem

- name: Generate fake certificates
  ansible.builtin.include_tasks: generate_selfsigned_certificate.yml
  vars:
    certificate_common_name: "{{ item }}"
  loop:
    - "{{ xui_fake_domain }}"
    - "{{ xui_fake_ip }}"
    - www.debian.org

- name: Ensure xui project dir exists {{ xui_project_dir }}
  ansible.builtin.file:
    path: "{{ xui_project_dir }}"
    state: directory
    mode: "0755"

- name: Install project files
  ansible.builtin.template:
    src: "{{ item.src }}.j2"
    dest: "{{ xui_project_dir }}/{{ item.src }}"
    owner: root
    group: root
    mode: "{{ item.mode | default('0600') }}"
  loop:
    - src: docker-compose.yaml
    # - src: env
    - src: nginx.conf
      mode: "0644"

- name: Copy decoy website to project dir `{{ xui_project_dir }}`
  ansible.builtin.copy:
    src: files/decoy.html
    dest: "{{ xui_project_dir }}/html/index.html"
    mode: "0644"

- name: Create download files
  community.general.filesize:
    path: "{{ xui_project_dir }}/html/{{ item }}mb"
    size: "{{ item }}m"
  loop:
    - 10
    - 20

# - name: Tear down existing compose services
#   community.docker.docker_compose:
#     project_src: "{{ xui_project_dir }}"
#     state: absent

- name: Ensure compose services are present
  community.docker.docker_compose:
    project_src: "{{ xui_project_dir }}"
    pull: true
    state: present

- name: Configure Panel
  ansible.builtin.command: docker compose --project-directory {{ xui_project_dir }} exec xui /app/x-ui setting -username {{ xui_sudo_username }} -password {{ xui_sudo_password }} -port {{ xui_port }} -enabletgbot -tgbotchatid {{ telegram_admin_id }} -tgbottoken {{ telegram_api_token }}

- name: Create and start xui service
  community.docker.docker_compose:
    project_src: "{{ xui_project_dir }}"
    services:
      - xui
    restarted: true

- name: Debug panel info
  ansible.builtin.debug:
    msg: |
      Panel URL: https://{{ xui_subdomain }}.{{ xui_domain }}:{{ xui_port }}
      sudo_user: {{ xui_sudo_username }}
      sudo_password: {{ xui_sudo_password }}
