---
- name: Restart xray service
  ansible.builtin.service:
    name: xray
    state: restarted

- name: Remove nginx socket files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /dev/shm/nginx-h1.sock
    - /dev/shm/nginx-h2c.sock

- name: Restart nginx service
  ansible.builtin.service:
    name: nginx
    state: restarted
