---
- name: Add A record to Cloudflare
  community.general.cloudflare_dns:
    account_email: "{{ cloudflare_email }}"
    account_api_key: "{{ cloudflare_api_key }}"
    zone: "{{ item.cloudflare_domain }}"
    name: "{{ item.cloudflare_subdomain }}"
    type: A
    value: "{{ ansible_host }}"
    ttl: 120
    # The record should be the only one for that record type and record name.
    solo: true
    state: present
  loop: "{{ records }}"